"""DiDi Food scraper for Mexico market — real endpoint architecture documented via network interception."""

import datetime
import logging
import re
from typing import Any

from .base_scraper import BaseScraper

logger = logging.getLogger(__name__)

# ─── DiDi Food web architecture (verified 2026-05-10 via Playwright network interception) ───
#
# Web app:  https://www.didi-food.com/es-MX/food/?pl={base64(poiJson)}
#           where poiJson = {"poiId":"...", "lat":..., "lng":..., ...}
#
# Login flow:
#   1. GET  https://www.didi-food.com/es-MX  → click .login-btn
#   2. Redirects to: https://page.didiglobal.com/public-biz/pc-login/3.0.8/index.html
#                    ?appid=120838&role=1&source=70001&country_id=484&lang=es-MX
#   3. Config:  GET  epassport.didiglobal.com/passport/login/v5/getAppConfig
#   4. Countries: GET epassport.didiglobal.com/passport/login/v5/getCountryList
#   5. Fill phone (MX: country_id=484) + password → POST to login endpoint
#   6. On success: redirects to c.didi-food.com/login/callback?redirectUrl=...
#   7. Cookie "ticket" set on .c.didi-food.com → grants access to restaurant feed
#
# Address APIs (no auth required, but need wsgsig):
#   POST  https://c.didi-food.com/address/getCurrentPoi?wsgsig={sig}
#         body (form-encoded): lat, lng, poiId, cityId, countyId, ...
#         returns: {"errno":0, "data": {"address": {"poi": {poiId, lat, lng, displayName, ...}}}}
#
#   POST  https://c.didi-food.com/address/textSearch?wsgsig={sig}
#         body (form-encoded): keyword, lat, lng, cityId, ...
#         returns: list of POI candidates
#
# Anti-bot / request signing:
#   All c.didi-food.com calls require wsgsig = "dd05-{signature}"
#   Signature is generated by DiDi's JS security SDK:
#     POST https://api-sec.didiglobal.com/sign/v1/wsgsigsession/signinit
#          body: {"diuu":"{deviceUUID}", "bizId":"...", "sdkVer":"5.0.12", "os":"4", "appVer":"2.0.0"}
#          returns: {"noiss":..., "cpTe":"12", "epTe":...}
#   The SDK is obfuscated; signatures cannot be replicated outside a browser context.
#
# Restaurant feed: REQUIRES AUTHENTICATION (ticket cookie on .c.didi-food.com)
#   The feed page shows "Iniciar sesión" for unauthenticated sessions.
#   Chrome 147 uses app-bound encryption — cookies cannot be extracted for reuse.
#   Playwright launch_persistent_context with real Chrome profile blocked by Chrome 147 security.
#   Conclusion: DiDi Food web is behind auth — ALWAYS mock_fallback until session reuse solved.
#
# ────────────────────────────────────────────────────────────────────────────────────────────

FEED_BASE = "https://www.didi-food.com/es-MX/food/"
ADDRESS_API = "https://c.didi-food.com/address"


class DidiFoodScraper(BaseScraper):
    """DiDi Food scraper — returns mock_fallback records.

    DiDi Food requires authenticated web sessions for restaurant data. Their
    wsgsig anti-bot signatures are generated by an obfuscated JS SDK that cannot
    be replicated outside a real browser. Confirmed via full network interception
    on 2026-05-10: only address resolution APIs are reachable without auth.
    """

    def __init__(self) -> None:
        super().__init__(platform="didifood")

    def scrape(self, address: dict[str, Any], products: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Return mock_fallback records — DiDi Food requires authentication for feed data."""
        self.logger.info(
            "[didifood] auth-gated — returning mock_fallback for %s (%d products)",
            address.get("city", ""),
            len(products),
        )
        return [self._mock_fallback_record(address, p) for p in products]

    def _mock_fallback_record(self, address: dict[str, Any], product: dict[str, Any]) -> dict[str, Any]:
        restaurant = product.get("restaurant") or product.get("store", "")
        return {
            "timestamp": datetime.datetime.utcnow().isoformat(),
            "scraping_mode": "mock_fallback",
            "platform": "didifood",
            "city": address.get("city", ""),
            "zone_type": address.get("zone_type", ""),
            "address_id": address.get("id", ""),
            "address_full": address.get("address", ""),
            "product_name": product.get("name", ""),
            "product_category": product.get("category", ""),
            "restaurant_name": restaurant,
            "product_price_mxn": None,
            "delivery_fee_mxn": None,
            "service_fee_mxn": None,
            "total_price_mxn": None,
            "estimated_delivery_min": None,
            "estimated_delivery_max": None,
            "active_discount": False,
            "discount_description": None,
            "discount_amount_mxn": None,
            "restaurant_available": False,
            "scraping_status": "mock_fallback",
            "error_message": (
                "DiDi Food web is auth-gated (ticket cookie on .c.didi-food.com). "
                "Login at page.didiglobal.com/public-biz/pc-login/3.0.8 requires phone+password. "
                "Automated login attempts trigger rate limiting (account lockout). "
                "Chrome 147 app-bound encryption blocks cookie extraction. "
                "wsgsig anti-bot signatures (dd05-*) require DiDi's obfuscated JS SDK. "
                "mock_fallback is the correct production strategy."
            ),
        }
